### ISSUE TITLE
Broken Link on Main Page

### ISSUE THREAD

**Issue by billdenney** [mrgsolve/mrgsolve.github.io#1]
Hi @kylebaron, 

I just clicked on the "Quick hit demos" link on the main page, and the link is broken (going to https://mrgsolve.github.io/2017/02/23/quick).

**Comment by kylebaron** [comment]
Thanks; I'll take a look.

**Comment by kylebaron** [comment]
Linked over here now: https://mrgsolve.github.io/vignettes/quick.html

I had bigger plans for this when I did it a couple of years ago.  Added a couple items off the top of my head (against better judgement), but hope to get more in there. 

Thank you for taking the time to report, @billdenney

**Comment by billdenney** [comment]
Thanks!
